# -*- coding: utf-8 -*-
"""chatbot_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBvzgo8xXs_BASXAUJwmp69rdNFdiVwQ
"""

import telebot
import google.generativeai as genai
import time

# --- CONFIGURACIÓN ---
TELEGRAM_TOKEN = '8207267321:AAGrMpppXlaxeRYje5gpRp8hGPF6DRCA9Io'
GEMINI_API_KEY = 'AIzaSyDcrDwYzEGv8Ab0xzHY_fYKkJR64lYQA3s'

# Configuración de Google AI
genai.configure(api_key=GEMINI_API_KEY)

def configurar_modelo():
    try:
        # Buscamos modelos con un pequeño reintento por si hay timeout
        modelos = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
        seleccionado = next((m for m in modelos if '1.5-flash' in m), modelos[0])

        config_humana = {
            "temperature": 0.8,
            "top_p": 0.95,
            "max_output_tokens": 1024,
        }

        instrucciones = (
            "Eres un asistente amigable y educado llamado 'Bot de Fernando'. "
            "Responde siempre en español con excelente ortografía. Usa emojis de forma natural. "
            "Si el usuario dice 'hola', recuerda saludar mencionando que fuiste creado por Fernando."
        )

        return genai.GenerativeModel(
            model_name=seleccionado,
            generation_config=config_humana,
            system_instruction=instrucciones
        )
    except Exception as e:
        print(f"Reintentando conexión... Error: {e}")
        time.sleep(5)
        return configurar_modelo()

model = configurar_modelo()
bot = telebot.TeleBot(TELEGRAM_TOKEN)

@bot.message_handler(func=lambda message: True)
def handle_all_messages(message):
    try:
        texto = message.text.lower().strip()

        # Tu saludo especial con ortografía perfecta
        if texto == "hola":
            bot.reply_to(message, "¡Hola! 👋 Soy un bot creado por Fernando. ¿En qué puedo ayudarte hoy? 😊")
            return

        bot.send_chat_action(message.chat.id, 'typing')
        response = model.generate_content(message.text)

        if response.text:
            bot.reply_to(message, response.text)

    except Exception as e:
        # Si es un error de saturación (muchos mensajes)
        if "429" in str(e):
            bot.reply_to(message, "¡Uff! Dame un respiro de un minutito, Fernando. ¡He hablado demasiado! ☕")
        else:
            bot.reply_to(message, "Perdona, se me cortó la señal un segundo. ¿Me lo repites? 😅")

print("---------------------------------------")
print("✅ Bot de Fernando: ONLINE y HUMANO")
print("---------------------------------------")
bot.infinity_polling()